services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_db
    ports:
      - "5432:5432"
    volumes:
      - account_management:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/account-0.0.1-SNAPSHOT-exec.jar
    container_name: account-management
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/account_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  account_management:
