services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_db
    ports:
      - "5432:5432"
    volumes:
      - account_management:/var/lib/postgresql/data

volumes:
  account_management:
