spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    schemas:
      - account_db
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    by.alex.account: DEBUG
  file:
    name: app.log
    path: logs
